version: '1'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=karam
      - POSTGRES_PASSWORD=karam
      - POSTGRES_DB=db

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=karam
      - POSTGRES_PASSWORD=karam
      - POSTGRES_DB=db

volumes:
  data: