# Generated by Django 4.2.2 on 2023-06-29 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Blog',
        ),
    ]
